"use client";

import Image from "next/image";
import { useEffect, useRef, useState, type ChangeEvent, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { AppShell, type Profile } from "./app-shell";
import { getSupabaseBrowserClient } from "../lib/supabase";
import { formatBytes, prepareImage, type PreparedImage } from "../lib/image-compression";

type Named = { id: string; name: string };
type PartRecord = { id: string; description: string; manufacturer_id: string | null; manufacturer_part_number: string | null; internal_part_number: string | null; notes: string | null; supply_type: string; status: string };
type Machine = { id: string; model: string; name: string | null; manufacturer_id: string; manufacturer?: Named | null };
type MachineRow = { manufacturer_id: string; machine_id: string };
type SupplierRow = { supplier_id: string; supplier_part_number: string; ordering_information: string; notes: string; preference_rank: number };
type PartOption = { id: string; description: string; internal_part_number: string | null };
type ExistingImage = { id: string; storage_path: string; caption: string | null; kind: string; sort_order: number; signedUrl?: string };
const emptySupplier = (rank: number): SupplierRow => ({ supplier_id: "", supplier_part_number: "", ordering_information: "", notes: "", preference_rank: rank });

export function AdminPartEditor({ partId }: { partId: string }) {
  const router = useRouter(); const previewUrls = useRef<string[]>([]);
  const [part, setPart] = useState<PartRecord | null>(null); const [manufacturers, setManufacturers] = useState<Named[]>([]); const [suppliers, setSuppliers] = useState<Named[]>([]); const [machines, setMachines] = useState<Machine[]>([]); const [parts, setParts] = useState<PartOption[]>([]);
  const [supplierRows, setSupplierRows] = useState<SupplierRow[]>([emptySupplier(1), emptySupplier(2), emptySupplier(3)]); const [machineRows, setMachineRows] = useState<MachineRow[]>([]); const [relatedIds, setRelatedIds] = useState<string[]>([]);
  const [images, setImages] = useState<ExistingImage[]>([]); const [removedImages, setRemovedImages] = useState<ExistingImage[]>([]); const [newImages, setNewImages] = useState<PreparedImage[]>([]); const [processingImages, setProcessingImages] = useState(false);
  const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");

  useEffect(() => { const supabase = getSupabaseBrowserClient(); if (!supabase) return; Promise.all([
    supabase.from("parts").select("id,description,manufacturer_id,manufacturer_part_number,internal_part_number,notes,supply_type,status").eq("id", partId).single(),
    supabase.from("manufacturers").select("id,name").eq("is_active", true).order("name"), supabase.from("suppliers").select("id,name").eq("is_active", true).order("name"),
    supabase.from("machines").select("id,model,name,manufacturer_id,manufacturer:manufacturers(id,name)").eq("is_active", true).order("model"), supabase.from("parts").select("id,description,internal_part_number").neq("id", partId).eq("status", "active").order("description"),
    supabase.from("part_suppliers").select("supplier_id,supplier_part_number,ordering_information,notes,preference_rank").eq("part_id", partId).eq("is_active", true).order("preference_rank"),
    supabase.from("part_machine_revisions").select("revision:machine_revisions(machine_id,machine:machines(manufacturer_id))").eq("part_id", partId), supabase.from("commonly_ordered_parts").select("related_part_id").eq("part_id", partId),
    supabase.from("part_images").select("id,storage_path,caption,kind,sort_order").eq("part_id", partId).order("sort_order"),
  ]).then(async ([partResult, manufacturerResult, supplierResult, machineResult, partsResult, linksResult, compatibilityResult, relatedResult, imageResult]) => {
    if (partResult.error) { setMessage(partResult.error.message); return; } setPart(partResult.data as PartRecord); setManufacturers((manufacturerResult.data ?? []) as Named[]); setSuppliers((supplierResult.data ?? []) as Named[]); setMachines((machineResult.data ?? []) as unknown as Machine[]); setParts((partsResult.data ?? []) as PartOption[]);
    const loadedSuppliers = (linksResult.data ?? []) as SupplierRow[]; setSupplierRows(Array.from({ length: 3 }, (_, index) => loadedSuppliers[index] ? { ...loadedSuppliers[index], preference_rank: index + 1 } : emptySupplier(index + 1)));
    setMachineRows((compatibilityResult.data ?? []).flatMap((row) => { const revision = row.revision as unknown as { machine_id: string; machine?: { manufacturer_id: string } | null } | null; return revision?.machine_id ? [{ machine_id: revision.machine_id, manufacturer_id: revision.machine?.manufacturer_id ?? "" }] : []; })); setRelatedIds((relatedResult.data ?? []).map((row) => row.related_part_id));
    if (imageResult.data?.length) { const rows = imageResult.data as ExistingImage[]; const { data: signed } = await supabase.storage.from("part-images").createSignedUrls(rows.map((image) => image.storage_path), 3600); setImages(rows.map((image, index) => ({ ...image, signedUrl: signed?.[index]?.signedUrl }))); }
  }); const urls = previewUrls.current; return () => urls.forEach(URL.revokeObjectURL); }, [partId]);

  function field(name: keyof PartRecord, value: string) { setPart((current) => current ? { ...current, [name]: value } : current); }
  function updateSupplier(index: number, name: keyof SupplierRow, value: string) { setSupplierRows((current) => current.map((row, rowIndex) => rowIndex === index ? { ...row, [name]: value } : row)); }
  function updateMachine(index: number, name: keyof MachineRow, value: string) { setMachineRows((current) => current.map((row, rowIndex) => rowIndex === index ? { ...row, [name]: value, ...(name === "manufacturer_id" ? { machine_id: "" } : {}) } : row)); }
  async function selectImages(event: ChangeEvent<HTMLInputElement>) { const selected = Array.from(event.target.files ?? []); event.target.value = ""; if (!selected.length) return; if (images.length + newImages.length + selected.length > 12) { setMessage("A part can have a maximum of 12 images."); return; } setProcessingImages(true); setMessage(""); try { const prepared = await Promise.all(selected.map(prepareImage)); previewUrls.current.push(...prepared.map((image) => image.previewUrl)); setNewImages((current) => [...current, ...prepared]); } catch (error) { setMessage(error instanceof Error ? error.message : "Images could not be processed."); } setProcessingImages(false); }
  function removeExisting(image: ExistingImage) { setImages((current) => current.filter((item) => item.id !== image.id)); setRemovedImages((current) => [...current, image]); }
  function removeNew(index: number) { setNewImages((current) => { URL.revokeObjectURL(current[index].previewUrl); return current.filter((_, imageIndex) => imageIndex !== index); }); }

  async function save(event: FormEvent, profile: Profile) {
    event.preventDefault(); if (!part) return; setSaving(true); setMessage(""); const supabase = getSupabaseBrowserClient(); if (!supabase) return;
    try {
    const updated = await supabase.from("parts").update({ description: part.description, manufacturer_id: part.manufacturer_id || null, manufacturer_part_number: part.manufacturer_part_number || null, internal_part_number: part.internal_part_number || null, notes: part.notes || null, supply_type: part.supply_type, status: part.status, updated_by: profile.id, updated_at: new Date().toISOString() }).eq("id", partId);
    if (updated.error) { setMessage(updated.error.message); setSaving(false); return; }
    await supabase.from("part_suppliers").delete().eq("part_id", partId); const activeSuppliers = supplierRows.filter((row) => row.supplier_id); if (activeSuppliers.length) { const result = await supabase.from("part_suppliers").insert(activeSuppliers.map((row, index) => ({ part_id: partId, supplier_id: row.supplier_id, supplier_part_number: row.supplier_part_number || null, ordering_information: row.ordering_information || null, notes: row.notes || null, preference_rank: index + 1 }))); if (result.error) { setMessage(result.error.message); setSaving(false); return; } }
    await supabase.from("part_machine_revisions").delete().eq("part_id", partId); for (const row of machineRows.filter((item) => item.machine_id)) { let revisionId: string | null = null; const existing = await supabase.from("machine_revisions").select("id").eq("machine_id", row.machine_id).eq("is_active", true).limit(1).maybeSingle(); revisionId = existing.data?.id ?? null; if (!revisionId) { const created = await supabase.from("machine_revisions").insert({ machine_id: row.machine_id, revision: "Default" }).select("id").single(); revisionId = created.data?.id ?? null; } if (revisionId) await supabase.from("part_machine_revisions").upsert({ part_id: partId, machine_revision_id: revisionId }, { onConflict: "part_id,machine_revision_id" }); }
    await supabase.from("commonly_ordered_parts").delete().eq("part_id", partId); if (relatedIds.length) await supabase.from("commonly_ordered_parts").insert(relatedIds.map((related_part_id) => ({ part_id: partId, related_part_id, created_by: profile.id })));
    for (const image of removedImages) { const row = await supabase.from("part_images").delete().eq("id", image.id); if (row.error) { setMessage(row.error.message); setSaving(false); return; } void supabase.storage.from("part-images").remove([image.storage_path]).then(() => undefined); }
    for (const [index, image] of newImages.entries()) { const path = `${partId}/${crypto.randomUUID()}.webp`; const storage = await supabase.storage.from("part-images").upload(path, image.file, { contentType: "image/webp" }); if (storage.error) { setMessage(storage.error.message); setSaving(false); return; } const row = await supabase.from("part_images").insert({ part_id: partId, storage_path: path, uploaded_by: profile.id, kind: "other", sort_order: images.length + index }); if (row.error) { setMessage(row.error.message); setSaving(false); return; } }
    router.push(`/parts/${partId}`); router.refresh();
    } catch (error) { setMessage(error instanceof Error ? error.message : "The part could not be saved. Please try again."); } finally { setSaving(false); }
  }

  return <AppShell requireAdmin>{(profile) => <main className="workspace form-workspace"><a className="back-link" href={`/parts/${partId}`}>← Back to part</a>{!part ? <section className="detail-state"><div className="spinner"/><p>{message || "Loading part…"}</p></section> : <form className="record-form" onSubmit={(event) => save(event, profile)}><section className="workspace-heading"><div><p className="eyebrow accent">Administrator editor</p><h1>Edit part</h1><p>Update approved information, relationships and images.</p></div></section>
    <section className="form-card"><div className="detail-card-heading"><h2>Part information</h2></div><div className="form-grid"><label className="span-2">Part Description *<input required value={part.description} onChange={(event) => field("description", event.target.value)}/></label><label>Part manufacturer<select value={part.manufacturer_id ?? ""} onChange={(event) => field("manufacturer_id", event.target.value)}><option value="">Not specified</option>{manufacturers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Part Number Manufacturer<input value={part.manufacturer_part_number ?? ""} onChange={(event) => field("manufacturer_part_number", event.target.value)}/></label><label>Company part number<input value={part.internal_part_number ?? ""} onChange={(event) => field("internal_part_number", event.target.value)}/></label><label>Supply type<select value={part.supply_type} onChange={(event) => field("supply_type", event.target.value)}><option value="unknown">Unknown</option><option value="local">Local</option><option value="dfl">DFL</option></select></label><label>Status<select value={part.status} onChange={(event) => field("status", event.target.value)}><option value="active">Active</option><option value="inactive">Inactive</option><option value="obsolete">Obsolete</option></select></label><label className="span-2">Notes<textarea rows={5} value={part.notes ?? ""} onChange={(event) => field("notes", event.target.value)}/></label></div></section>
    <section className="form-card"><div className="detail-card-heading"><h2>Machine compatibility</h2><button type="button" className="button secondary compact" onClick={() => setMachineRows((current) => [...current, { manufacturer_id: "", machine_id: "" }])}>+ Add machine</button></div>{machineRows.length ? <div className="machine-link-list">{machineRows.map((row, index) => <div className="machine-link-row" key={index}><label>Manufacturer<select value={row.manufacturer_id} onChange={(event) => updateMachine(index, "manufacturer_id", event.target.value)}><option value="">Select manufacturer</option>{manufacturers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Machine<select value={row.machine_id} onChange={(event) => updateMachine(index, "machine_id", event.target.value)} disabled={!row.manufacturer_id}><option value="">Select machine</option>{machines.filter((machine) => machine.manufacturer_id === row.manufacturer_id).map((machine) => <option key={machine.id} value={machine.id}>{machine.name ?? machine.model} · {machine.model}</option>)}</select></label><button type="button" className="icon-remove" onClick={() => setMachineRows((current) => current.filter((_, rowIndex) => rowIndex !== index))}>×</button></div>)}</div> : <p className="empty-detail">No machines linked.</p>}</section>
    <section className="form-card"><div className="detail-card-heading"><h2>Preferred suppliers</h2><span>Up to three</span></div><div className="supplier-form-list">{supplierRows.map((row, index) => <div className="supplier-form-row" key={index}><span>{index + 1}</span><label>Supplier<select value={row.supplier_id} onChange={(event) => updateSupplier(index, "supplier_id", event.target.value)}><option value="">Not selected</option>{suppliers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Supplier part number<input value={row.supplier_part_number ?? ""} onChange={(event) => updateSupplier(index, "supplier_part_number", event.target.value)}/></label><label>Ordering information<input value={row.ordering_information ?? ""} onChange={(event) => updateSupplier(index, "ordering_information", event.target.value)}/></label></div>)}</div></section>
    <section className="form-card"><div className="detail-card-heading"><h2>Related parts</h2></div><div className="form-grid"><label className="span-2">Commonly ordered parts<select multiple value={relatedIds} onChange={(event) => setRelatedIds(Array.from(event.target.selectedOptions, (option) => option.value))}>{parts.map((item) => <option key={item.id} value={item.id}>{item.internal_part_number ?? "No internal number"} · {item.description}</option>)}</select></label></div></section>
    <section className="form-card"><div className="detail-card-heading"><h2>Part images</h2><span>{images.length + newImages.length} retained</span></div><div className="image-admin-body"><label className="image-picker">Add images<input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={selectImages} disabled={processingImages}/><small>{processingImages ? "Compressing images…" : "New images are compressed to WebP before upload. Maximum 12 images."}</small></label><div className="upload-preview-grid">{images.map((image, index) => image.signedUrl ? <article key={image.id}><Image unoptimized width={360} height={270} src={image.signedUrl} alt={`Part image ${index + 1}`}/><div><strong>{image.caption ?? `Image ${index + 1}`}</strong><small>Existing image</small></div><button type="button" onClick={() => removeExisting(image)}>×</button></article> : null)}{newImages.map((image, index) => <article key={image.previewUrl}><Image unoptimized width={360} height={270} src={image.previewUrl} alt={`New part image ${index + 1}`}/><div><strong>{image.file.name}</strong><small>{formatBytes(image.originalBytes)} → {formatBytes(image.compressedBytes)}</small></div><button type="button" onClick={() => removeNew(index)}>×</button></article>)}</div></div></section>
    {message && <p className="form-message">{message}</p>}<div className="form-actions"><a className="button secondary" href={`/parts/${partId}`}>Cancel</a><button className="button primary" disabled={saving || processingImages}>{saving ? "Saving…" : "Save part changes"}</button></div></form>}</main>}</AppShell>;
}
