'use client';
import { useEffect, useState } from 'react';
import { getSupabaseBrowserClient } from '../lib/supabase';

type Reference = { id: string; title: string; category: string; body: string; source_url: string; revision: number; updated_at: string; status: 'draft'|'checked'; };
const categories = ['Pinouts','Threads','Connectors','Bolt heads','Other'];
const intel = 'https://edc.intel.com/content/www/us/en/design/ipla/software-development-platforms/client/platforms/alder-lake-desktop/atx-version-3-0-multi-rail-desktop-platform-power-supply-design-guide/2.0/main-power-connector-required/';
const starters = [
  {title:'ATX 24-pin main power',category:'Pinouts',body:'Main motherboard connector only, using Intel ATX 3.0 guide v2.0. Confirm moulded pin numbers and the viewing direction in the source drawing. This table is not a physical connector view. Modular PSU-side connectors and ATX12VO use different arrangements.',source:intel,headers:['Pins','Signal'],rows:[['1, 2, 12, 13','+3.3 V (pin 13 also sense)'],['3, 5, 7, 15, 17, 18, 19, 24','COM / ground'],['4, 6, 21, 22, 23','+5 V'],['8','PWR_OK'],['9','+5 V standby'],['10, 11','+12 V'],['14','−12 V'],['16','PS_ON#'],['20','Reserved / not connected']]},
  {title:'Reading a thread designation',category:'Threads',body:'Metric pitch is the distance between threads in millimetres. Inch thread count is expressed as threads per inch (TPI). Match both diameter and pitch; a similar-looking screw is not proof of compatibility.',source:'https://boltdepot.com/Fastener-Information/Measuring/Notation',headers:['Example','Meaning'],rows:[['M6 × 1.0 × 20','6 mm nominal diameter · 1 mm pitch · 20 mm length'],['1/4–20 × 1','1/4 inch diameter · 20 TPI · 1 inch length'],['UNC / UNF','Unified coarse / fine thread series']]},
  {title:'Connector family starting points',category:'Connectors',body:'Measure contact pitch centre-to-centre, then compare the housing, keying, latch, terminal type and circuit count. Family and pitch alone do not establish interchangeability or current rating.',source:'https://supplychain.molex.com/content/molex/molex-dot-com/language-masters/en/products/connectors/fit-family-connectors.html',headers:['Molex family','Nominal pitch'],rows:[['Nano-Fit','2.50 mm'],['Micro-Fit','3.00 mm'],['Ultra-Fit','3.50 mm'],['Mini-Fit','4.20 mm']]},
  {title:'Head style versus drive type',category:'Bolt heads',body:'Record head shape separately from the tool recess. Measure an ordinary raised-head fastener from beneath the head; countersunk flat-head screws include the head in their length.',source:'https://boltdepot.com/Fastener-Information/Identifying-Fasteners',headers:['Head styles','Drive examples'],rows:[['Hex, pan, button','External hex, internal hex'],['Flat / countersunk','Slotted, Phillips'],['Socket cap, carriage','Six-lobe / Torx; carriage has no recess']]},
];
async function previewRefs(write?: Reference): Promise<Reference[]> {
  return new Promise((resolve,reject)=>{const request=indexedDB.open('partsdb-bench-preview-v1',1);request.onupgradeneeded=()=>request.result.createObjectStore('references',{keyPath:'id'});request.onerror=()=>reject(new Error('Device storage is unavailable.'));request.onsuccess=()=>{const db=request.result,tx=db.transaction('references',write?'readwrite':'readonly'),store=tx.objectStore('references');let rows:Reference[]=[];if(write){const get=store.get(write.id);get.onsuccess=()=>{if(get.result&&get.result.revision!==write.revision-1){tx.abort();return;}store.put(write);const all=store.getAll();all.onsuccess=()=>{rows=all.result;};};}else{const all=store.getAll();all.onsuccess=()=>{rows=all.result;};}tx.oncomplete=()=>{db.close();resolve(rows);};tx.onerror=tx.onabort=()=>{db.close();reject(new Error('Reference could not be saved, or another tab changed it. Export your note before reloading.'));};};});
}
export function BenchReferences({preview,readonly}:{preview:boolean;readonly:boolean}) {
  const [search,setSearch]=useState(''),[category,setCategory]=useState('All'),[custom,setCustom]=useState<Reference[]>([]),[editing,setEditing]=useState<Reference|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{let alive=true;(async()=>{try{if(preview){const data=await previewRefs();if(alive)setCustom(data);}else{const db=getSupabaseBrowserClient();if(!db)throw new Error('Database not connected.');const {data,error}=await db.from('bench_references').select('*').order('updated_at',{ascending:false});if(error)throw error;if(alive)setCustom(data??[]);}}catch(e){if(alive)setError(e instanceof Error?e.message:'Custom references could not be loaded.');}})();return()=>{alive=false;};},[preview]);
  useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(editing){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[editing]);
  async function save(){if(!editing)return;setBusy(true);setError('');try{if(!editing.title.trim()||!editing.body.trim())throw new Error('Add a title and reference notes.');if(editing.source_url&&!/^https?:\/\//i.test(editing.source_url))throw new Error('Source links must start with https:// or http://.');const saved={...editing,revision:editing.revision+1,updated_at:new Date().toISOString()};if(preview)setCustom(await previewRefs(saved));else{const db=getSupabaseBrowserClient();if(!db)throw new Error('Database not connected.');const {data:user}=await db.auth.getUser();if(!user.user)throw new Error('Sign in again.');const query=editing.revision===0?db.from('bench_references').insert({...saved,owner_id:user.user.id}):db.from('bench_references').update(saved).eq('id',saved.id).eq('revision',editing.revision);const result=await query.select().single();if(result.error)throw new Error('Save failed or this reference changed on another device. Your note remains open.');setCustom(all=>[saved,...all.filter(x=>x.id!==saved.id)]);}setEditing(null);}catch(e){setError(e instanceof Error?e.message:'Save failed.');}finally{setBusy(false);}}
  function exportNotes(){const url=URL.createObjectURL(new Blob([JSON.stringify({format:'PartsDB bench references',version:1,references:custom,...(editing?{unsaved_note:editing}:{})},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='bench-references.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
  function match(item:{title:string;category:string;body:string}){return(category==='All'||item.category===category)&&`${item.title} ${item.body} ${item.category}`.toLowerCase().includes(search.toLowerCase());}
  return <section><div className="wk-ref-toolbar"><label className="wk-label">Search references<input placeholder="ATX, pitch, Molex, hex…" value={search} onChange={e=>setSearch(e.target.value)}/></label><label className="wk-label">Category<select value={category} onChange={e=>setCategory(e.target.value)}><option>All</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label><div className="wk-ref-actions"><button className="button primary" disabled={readonly||busy||!!editing} onClick={()=>setEditing({id:crypto.randomUUID(),title:'',category:'Other',body:'',source_url:'',revision:0,updated_at:'',status:'draft'})}>＋ Add reference</button><button className="button secondary" onClick={exportNotes}>Export notes</button></div></div>
    {error&&<p className="wk-alert" role="alert">{error}</p>}
    {editing&&<div className="wk-ref-editor"><h2>{editing.revision?'Edit reference':'New reference'}</h2><label className="wk-label">Title<input value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><label className="wk-label">Category<select value={editing.category} onChange={e=>setEditing({...editing,category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label className="wk-label">Reference notes<textarea rows={6} value={editing.body} onChange={e=>setEditing({...editing,body:e.target.value})}/></label><label className="wk-label">Source URL<input type="url" value={editing.source_url} onChange={e=>setEditing({...editing,source_url:e.target.value})}/></label><label className="wk-label">Review status<select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value as Reference['status']})}><option value="draft">Draft / needs checking</option><option value="checked">Checked by me</option></select></label><div className="wk-ref-actions"><button disabled={busy||readonly} className="button primary" onClick={()=>void save()}>Save reference</button><button disabled={busy} className="button secondary" onClick={()=>{if(window.confirm('Discard this reference edit?'))setEditing(null);}}>Cancel</button></div></div>}
    <div className="wk-ref-grid">{custom.filter(match).map(r=><article className="wk-ref-card" key={r.id}><p className="wk-eyebrow">{r.category} · YOUR NOTE</p><h2>{r.title}</h2><p className="wk-ref-note">{r.body}</p>{/^https?:\/\//i.test(r.source_url)&&<a className="wk-ref-source" href={r.source_url} target="_blank" rel="noreferrer">Open source</a>}<p className="wk-ref-meta">{r.status==='checked'?'Checked by you':'Draft / needs checking'} · Revision {r.revision} · {r.updated_at.slice(0,10)}</p><button className="button secondary" disabled={readonly||busy||!!editing} onClick={()=>setEditing(r)}>Edit reference</button></article>)}{starters.filter(match).map(r=><article className="wk-ref-card" key={r.title}><p className="wk-eyebrow">{r.category} · STARTER REFERENCE</p><h2>{r.title}</h2><p>{r.body}</p><div className="wk-ref-table-scroll"><table><thead><tr>{r.headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{r.rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{cell}</td>)}</tr>)}</tbody></table></div><a className="wk-ref-source" href={r.source} target="_blank" rel="noreferrer">Source: {r.category==='Pinouts'?'Intel ATX design guide':r.category==='Connectors'?'Molex Fit family':'Bolt Depot fastener reference'}</a><p className="wk-ref-meta">Source reviewed 5 October 2026 · Revision 1</p></article>)}</div>
    {!custom.filter(match).length&&!starters.filter(match).length&&<div className="wk-empty">No references match your search.</div>}
  </section>;
}
