'use client';
/* eslint-disable @next/next/no-img-element -- Images are already compressed and use private signed or device-local URLs. */
import { useEffect, useRef, useState, type ChangeEvent } from 'react';
import { categories, emptyReference, exportReferences, loadReferences, prepareReferencePhoto, prepareReferenceDocument, downloadReferenceDocument, saveReference, type Reference, type ReferenceDocument } from '../lib/bench-references';
import { formatBytes } from '../lib/image-compression';
import { starters } from '../lib/bench-starters';

export function BenchReferences({preview,readonly}:{preview:boolean;readonly:boolean}) {
  const [search,setSearch]=useState(''),[category,setCategory]=useState(''),[subcategory,setSubcategory]=useState(''),[custom,setCustom]=useState<Reference[]>([]),[editing,setEditing]=useState<Reference|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[message,setMessage]=useState('');
  const pdfInput=useRef<HTMLInputElement>(null),gallery=useRef<HTMLInputElement>(null),camera=useRef<HTMLInputElement>(null),editor=useRef<HTMLDivElement>(null);
  const availableCategories=[...new Set([...categories,...custom.map(r=>r.category),...(editing?[editing.category]:[])].filter(Boolean))].sort();
  const subcategories=[...new Set(custom.filter(r=>!category||r.category===category).map(r=>r.subcategory).filter(Boolean))].sort();
  const editingSubcategories=[...new Set(custom.filter(r=>r.category.toLowerCase()===editing?.category.toLowerCase()).map(r=>r.subcategory).filter(Boolean))].sort();
  useEffect(()=>{let alive=true;loadReferences(preview).then(data=>{if(alive)setCustom(data);}).catch(e=>{if(alive)setError(e instanceof Error?e.message:'References could not be loaded.');}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[preview]);
  useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(editing){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[editing]);
  const editingId=editing?.id;
  useEffect(()=>{if(editingId)editor.current?.scrollIntoView({behavior:'smooth',block:'start'});},[editingId]);
  function edit(r:Reference){setEditing(r);setMessage('');setError('');}
  async function save(){if(!editing||readonly)return;setBusy(true);setError('');try{
    const categoryName=editing.category.trim();if(!categoryName||categoryName.length>80)throw new Error('Enter a category of 1 to 80 characters.');
    const canonical=availableCategories.find(c=>c.toLowerCase()===categoryName.toLowerCase())??categoryName;
    const subName=editing.subcategory.trim();const canonicalSub=editingSubcategories.find(c=>c.toLowerCase()===subName.toLowerCase())??subName;
    const records=await saveReference({...editing,category:canonical,subcategory:canonicalSub},preview);setCustom(all=>[...records,...all.filter(r=>!records.some(s=>s.id===r.id))]);setEditing(null);setMessage('Reference saved.');
  }catch(e){setError(e instanceof Error?e.message:'Save failed.');}finally{setBusy(false);}}
  async function photos(event:ChangeEvent<HTMLInputElement>){const files=Array.from(event.target.files??[]);event.target.value='';if(!editing||readonly||!files.length)return;if(editing.photos.length+files.length>12){setError('Keep each reference to 12 photos or fewer.');return;}setBusy(true);setError('');const added=[];try{for(const file of files)added.push(await prepareReferencePhoto(file,editing.id,preview));}catch(e){setError(e instanceof Error?e.message:'Photo upload failed.');}finally{if(added.length)setEditing({...editing,photos:[...editing.photos,...added]});setBusy(false);}}
  async function documents(event:ChangeEvent<HTMLInputElement>){const files=Array.from(event.target.files??[]);event.target.value='';if(!editing||readonly||!files.length)return;if(editing.documents.length+files.length>10){setError('Keep each reference to 10 PDFs or fewer.');return;}setBusy(true);setError('');const added:ReferenceDocument[]=[];try{for(const file of files)added.push(await prepareReferenceDocument(file,editing.id,preview));}catch(e){setError(e instanceof Error?e.message:'PDF upload failed.');}finally{if(added.length)setEditing({...editing,documents:[...editing.documents,...added]});setBusy(false);}}
  async function downloadPdf(document:ReferenceDocument){setBusy(true);setError('');try{await downloadReferenceDocument(document);}catch(e){setError(e instanceof Error?e.message:'Download failed.');}finally{setBusy(false);}}
  async function exportNotes(){setBusy(true);setError('');try{await exportReferences(custom,editing);setMessage('Reference ZIP downloaded with notes, photos and PDFs.');}catch(e){setError(e instanceof Error?e.message:'Export failed.');}finally{setBusy(false);}}
  function match(item:{title:string;category:string;subcategory?:string;body:string}){return(category===''||item.category===category)&&(!subcategory||item.subcategory===subcategory)&&`${item.title} ${item.body} ${item.category} ${item.subcategory??''}`.toLowerCase().includes(search.toLowerCase());}
  const remainingStarters=starters.filter(r=>!custom.some(c=>c.starter_key===r.title));
  const locked=readonly||busy||loading;
  return <section>
    <div className="wk-ref-toolbar"><label className="wk-label">Search references<input placeholder="ATX, pitch, Molex, hex…" value={search} onChange={e=>setSearch(e.target.value)}/></label><label className="wk-label">Filter by category<select value={category} onChange={e=>{setCategory(e.target.value);setSubcategory('');}}><option value="">All categories</option>{availableCategories.map(c=><option key={c}>{c}</option>)}</select></label><label className="wk-label">Filter by subcategory<select value={subcategory} onChange={e=>setSubcategory(e.target.value)}><option value="">All subcategories</option>{subcategories.map(c=><option key={c}>{c}</option>)}</select></label><div className="wk-ref-actions"><button className="button primary" disabled={locked||!!editing} onClick={()=>edit(emptyReference())}>＋ Add reference</button><button className="button secondary" disabled={busy||loading} onClick={()=>void exportNotes()}>Export reference ZIP</button></div></div>
    {readonly&&<p className="wk-alert">Standby: references are available to view and export. Editing is disabled.</p>}
    {error&&<p className="wk-alert" role="alert">{error}</p>}{message&&<p className="wk-message" role="status">{message}</p>}
    {editing&&<div className="wk-ref-editor" ref={editor}><h2>{editing.revision?'Edit reference':editing.starter_key?'Edit starter reference':'New reference'}</h2>{editing.starter_key&&<p className="wk-small">Your saved edition replaces this starter in your library. Other users retain their own versions.</p>}
      <fieldset className="wk-fields" disabled={locked}>
      <label className="wk-label">Title<input maxLength={200} value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></label>
      <label className="wk-label">Category<input list="bench-category-options" maxLength={80} value={editing.category} placeholder="Choose or type a category" onChange={e=>setEditing({...editing,category:e.target.value})}/><datalist id="bench-category-options">{availableCategories.map(c=><option key={c} value={c}/>)}</datalist></label><p className="wk-small">Choose an existing category or type your own, such as Wiring, Claw machines or Power supplies.</p>
      <label className="wk-label">Subcategory<input list="bench-subcategory-options" maxLength={80} value={editing.subcategory} placeholder="Optional: choose or type a subcategory" onChange={e=>setEditing({...editing,subcategory:e.target.value})}/><datalist id="bench-subcategory-options">{editingSubcategories.map(c=><option key={c} value={c}/>)}</datalist></label><p className="wk-small">For example: Connectors → Molex, or Fasteners → Bolts.</p><label className="wk-label">Reference notes<textarea rows={8} value={editing.body} onChange={e=>setEditing({...editing,body:e.target.value})}/></label><label className="wk-label">Source URL<input type="url" value={editing.source_url} onChange={e=>setEditing({...editing,source_url:e.target.value})}/></label><label className="wk-label">Review status<select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value as Reference['status']})}><option value="draft">Draft / needs checking</option><option value="checked">Checked by me</option></select></label>
      <h3>Reference photos</h3><p className="wk-small">Up to 12 photos. Uses PartsDB compression: WebP, maximum 1600 px. Add a caption to explain each picture.</p>
      <input ref={gallery} type="file" accept="image/*" multiple hidden onChange={e=>void photos(e)}/><input ref={camera} type="file" accept="image/*" capture="environment" hidden onChange={e=>void photos(e)}/>
      <div className="wk-ref-actions"><button className="button secondary" onClick={()=>camera.current?.click()}>Take photo</button><button className="button secondary" onClick={()=>gallery.current?.click()}>Add pictures</button></div>
      <div className="wk-reference-photos">{editing.photos.map((p,i)=><figure key={p.id}><img src={p.imageUrl} alt={p.caption||`Reference photo ${i+1}`}/><label className="wk-label">Caption {i+1}<input value={p.caption} maxLength={500} onChange={e=>setEditing({...editing,photos:editing.photos.map(x=>x.id===p.id?{...x,caption:e.target.value}:x)})}/></label><button className="button secondary" onClick={()=>setEditing({...editing,photos:editing.photos.filter(x=>x.id!==p.id)})}>Remove photo {i+1}</button></figure>)}</div>
      <h3>PDF datasheets</h3><p className="wk-small">Up to 10 PDFs, 20 MB each. Original quality is preserved; PDFs are not automatically recompressed.</p><input ref={pdfInput} type="file" accept="application/pdf,.pdf" multiple hidden onChange={e=>void documents(e)}/><button className="button secondary" onClick={()=>pdfInput.current?.click()}>Add PDF datasheets</button><div className="wk-reference-documents">{editing.documents.map((d,i)=><div key={d.id}><label className="wk-label">PDF title {i+1}<input maxLength={200} value={d.name} onChange={e=>setEditing({...editing,documents:editing.documents.map(x=>x.id===d.id?{...x,name:e.target.value}:x)})}/></label><span>{formatBytes(d.bytes)}</span><button className="button secondary" onClick={()=>void downloadPdf(d)}>Download PDF</button><button className="button secondary" onClick={()=>setEditing({...editing,documents:editing.documents.filter(x=>x.id!==d.id)})}>Remove PDF {i+1}</button></div>)}</div>
      <div className="wk-ref-actions"><button className="button primary" onClick={()=>void save()}>{busy?'Working…':'Save reference'}</button><button className="button secondary" onClick={()=>{if(window.confirm('Discard this reference edit?'))setEditing(null);}}>Cancel</button></div>
      </fieldset></div>}
    {loading?<p>Loading references…</p>:<div className="wk-ref-grid">{custom.filter(match).map(r=><article className="wk-ref-card" key={r.id}><p className="wk-eyebrow">{r.category}{r.subcategory?` / ${r.subcategory}`:''} · YOUR {r.starter_key?'EDITION':'NOTE'}</p><h2>{r.title}</h2><p className="wk-ref-note">{r.body}</p><div className="wk-reference-photos">{r.photos.map((p,i)=><figure key={p.id}><a href={p.imageUrl} target="_blank" rel="noreferrer" aria-label={`Open ${p.caption||`photo ${i+1}`} full size`}><img loading="lazy" src={p.imageUrl} alt={p.caption||`Reference photo ${i+1}`}/></a>{p.caption&&<figcaption>{p.caption}</figcaption>}</figure>)}</div><div className="wk-reference-documents">{r.documents.map(d=><div key={d.id}><strong>{d.name}</strong><span>{formatBytes(d.bytes)}</span><button className="button secondary" disabled={busy} onClick={()=>void downloadPdf(d)}>Download PDF</button></div>)}</div>{/^https?:\/\//i.test(r.source_url)&&<a className="wk-ref-source" href={r.source_url} target="_blank" rel="noreferrer">Open source</a>}<p className="wk-ref-meta">{r.status==='checked'?'Checked by you':'Draft / needs checking'} · Revision {r.revision} · {r.updated_at.slice(0,10)}</p><button className="button secondary" disabled={locked||!!editing} onClick={()=>edit(r)}>Edit reference</button></article>)}{remainingStarters.filter(match).map(r=><article className="wk-ref-card" key={r.title}><p className="wk-eyebrow">{r.category} · STARTER REFERENCE</p><h2>{r.title}</h2><p>{r.body}</p><div className="wk-ref-table-scroll"><table><thead><tr>{r.headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{r.rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{cell}</td>)}</tr>)}</tbody></table></div><a className="wk-ref-source" href={r.source} target="_blank" rel="noreferrer">Open original source</a><p className="wk-ref-meta">Source reviewed 5 October 2026 · Revision 1</p><button className="button secondary" disabled={locked||!!editing} onClick={()=>edit({...emptyReference(),title:r.title,category:r.category,source_url:r.source,starter_key:r.title,body:r.body+'\n\n'+r.headers.join(' | ')+'\n'+r.rows.map(row=>row.join(' | ')).join('\n')})}>Edit reference</button></article>)}</div>}
    {!loading&&!custom.filter(match).length&&!remainingStarters.filter(match).length&&<div className="wk-empty">No references match your search.</div>}
  </section>;
}
